shopapp/urls.py
from django.urls import path
from .views import ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, SSListView
from . import views

urlpatterns = [
    path('plist/', ProductListView.as_view(), name='p_list'),
    path('<int:pk>/', ProductDetailView.as_view(), name='p_detail'),
    path('new/', ProductCreateView.as_view(), name='p_new'),
    path('<int:pk>/edit/', ProductUpdateView.as_view(), name='p_edit'),
    path('sslist/', SSListView.as_view(), name='ss_list'),
]

shopproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shopapp.urls'))
]

shopapp/models.py
from django.db import models
from django.urls import reverse # new

# Create your models here.
class Shop(models.Model):
    name = models.CharField(max_length=200)
    location = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('s_detail', args=[str(self.id)])

class Product(models.Model):
    name = models.CharField(max_length=200)
    exp_date = models.DateField()
    shop = models.ForeignKey(
        Shop,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('p_detail', args=[str(self.id)])

class Staff(models.Model):
    name = models.CharField(max_length=200)
    job = models.CharField(max_length=200)
    shop = models.ForeignKey(
        Shop,
        on_delete=models.CASCADE,
    )
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('st_detail', args=[str(self.id)])

shopapp/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView
from .models import Product, Shop

# Create your views here.
class ProductListView(ListView):
    model = Product
    template_name = 'plist.html'
    context_object_name = 'all_ps_list'

class ProductDetailView(DetailView):
    model = Product
    template_name = 'p_detail.html'

class ProductCreateView(CreateView):
    model = Product
    template_name = 'p_create.html'
    fields = ['name', 'exp_date', 'shop']

class ProductUpdateView(UpdateView):
    model = Product
    template_name = 'p_edit.html'
    fields = ['name']

class SSListView(ListView):
    model = Shop
    template_name = 'ss_list.html'
    context_object_name = 'all_s_list'

templates/p_create.html
<html>
<head>
    <title>Create</title>
</head>
<body>
        <h1>Create New Product</h1>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save" />
        </form>
</body>
</html>

templates/p_detail.html
<html>
<head>
    <title>Detail</title>
</head>
<body>
    <h1>Product Details Page</h1>
    <p>Name: {{ product.name }}</p>
    <p>Expiry Date: {{ product.exp_date }}</p>

    <p><a href="{% url 'p_edit' product.pk %}">+ Edit Product Record</a></p>
    
</body>
</html>

templates/p_edit.html
<html>
<head>
    <title>Edit</title>
</head>
<body>
        <h1>Edit Product</h1>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save" />
        </form>
</body>
</html>

templates/plist.html
<html>
<head>
    <title>List</title>
</head>
<body>
    <h1>Product List Page</h1>
    {% for p in all_ps_list %}
    <h3><a href="{% url 'p_detail' p.pk %}">{{ p.name }}</a></h3>
    {% endfor %}

    <h2><a href="{% url 'p_new' %}">+New Product</a></h2>
</body>
</html>

templates/ss_list.html
<html>
<head>
    <title>List</title>
</head>
<body>
    <h2>Shop & Staff List</h2>
    {% for s in all_s_list %}
        <h3>{{ s.name }}</h3>
        {% for st in s.staff_set.all %}
            <h4><li>{{ st.name }}</li></h4>
        {% endfor %}
    {% endfor %}
</body>
</html>